--- 
title: "Multivariate Cookbook"
author: "Ju-Chi Yu and Sheila Meldrum"
date: "`r Sys.Date()`"
lass: book
documentclass: book
output:
  bookdown::gitbook: 
    config:
      toc:
        collapse: section
        scroll_highlight: yes
      toolbar:
        position: static
      search: yes
  bookdown::pdf_book: default
description: "This book provides an introduction of simple and advanced multivariate analysis."
---

# Preface{-}

Multivariate techniques are becoming an increasingly popular analytical tool given the rise of both open and large datasets. This book hopes to provide conceptual and practical knowledge on how to perform these multivariate techniques.

## What are Multivariate Analyses? {-}

Multivariate analyses are used when there is more than one outcome (or dependent variables; DVs) as opposed to univariate analyses (e.g., ANOVA or regression) that have only one outcome. 

Component-based multivariate analyses are primarily data driven exploratory techniques of the underlying structure (i.e. latent structure) of a multivariate data set. These underlying structures are represented by a mixture of the original variables---called components or factors---which explains the most information about the observations.

## Multivariate vs. Univariate Analyses {-}

### When to Use Univariate Analyses? {-}

Univariate statistics statistics are most appropriate to use when you have one outcome (or dependent variable) and have planned inferences based on *a priori* hypotheses.

### When to Use Multivariate Techniques? {-}

1. Understand the relationship between two or more outcome variables/measurements.

    Note: A Principle Component Analysis (PCA) with two variables would be the same as a pearson correlation ($r$) if the variables are normalized (i.e., z-scored) first.

2. Exploratory data analysis

    When you don't have *a priori* hypotheses about the structure of your data. 

    Example: You are using a large archival data set that includes multiple behavioral measurements (i.e., surveys, performance data, etc).

3. Dimension reduction

    Example: Machine learning

4. Identify unique patterns across observations 

    Example: Eigen faces (maybe), time series data, functional PCA 

## Common Multivariate Analyses {-}

```{r echo=FALSE, results='asis'}
library(knitr)

TableCols <- c("Type of Data", "No. of Tables","Analysis", "Results") 
Quant1 <- c("Quantitative","1","PCA","Factor Scores, Column Loadings")
Quant2 <- c("Quantitative", "2", "PLS", "insert")
Quant3 <- c("Quantitative", "2", "BADA", "insert")
Quant4 <- c("Quantitative", "2+", "MFA", "insert")
Quant5 <- c("Quantitative", "2+", "STATIS", "insert")
Qual1 <- c("Qualitative", "1", "CA", "insert")
Qual2 <- c("Qualitative", "2+", "MCA", "insert")
Qual3 <- c("Qualitative", "2+", "PLS-CA", "insert")
Qual4 <- c("Mixed", "2+", "Mixed PLS", "insert")
tb <- rbind.data.frame(Quant1, Quant2, Quant3, Quant4, Quant5, Qual1, Qual2, Qual3, Qual4) 
colnames(tb) <- TableCols

kable(x = tb, row.names = FALSE, col.names = TableCols) #caption = "Common Multivariate Analyses")
```

## What Will this Book Cover? {-}

Currently, this book will cover PCA with other multivariate analyses being added over time.

## How Will this Book be Covered? {-}

Each multivariate technique will cover:

1. A conceptual description
2. A practical example of the technique using R and the `ExPosition` library
3. What `ExPosition` is actually doing behing the scenes using R
4. A walk-through of the math

For the practical example of each technique, we will cover:

1. Pre-processing of the data
2. Using descriptive statistics to describe the data
3. Performining the multivariate technique
4. Determining the number of components
5. Visualizing and interpreting the components

Hopefully, this format will allow individuals that are new to multivariate techniques to grasp both conceptual and pratical information of each technique while allowing more experienced individuals to use this book as a quick reference.