--- 
title: "Multivariate Cookbook"
author: "Ju-Chi Yu and Sheila Meldrum"
date: "`r Sys.Date()`"
lass: book
documentclass: book
output:
  bookdown::gitbook: 
    config:
      toc:
        collapse: section
        scroll_highlight: yes
      toolbar:
        position: static
      search: yes
  bookdown::pdf_book: default
description: "This book provides an introduction of simple and advanced multivariate analysis."
---

# Preface{-}

## Mulitvariate analyses vs. Univariate anlyses

What are multivariate analyses? 
Component-based multivariate methods are primarily data driven exploratory techniques of the underlying structure (i.e. latent structure) of a multivariate data set. These underlying structers are represted by a mixture of the original variables---called components or factors---which explain the most information about your observations.

When would I use multivariate instead of univariate analyses?
1. When you want to understand the relationship between multiple (2 +) outcome variables/measurements. 

Note a Principle Component Analysis (PCA) with two variables would be the same as a pearson correlation (r). 

2. Exploratory data analysis, when you don't have *a priori* hypotheses about the structure of your data. 

Example: You are using a large archival data set that includes multiple behavioral measurements (i.e., surveys, performance data, etc).

3. Dimention reduction

Example: Machine learning 

4. Identify unique patterns across observations 

Example: Eigen faces (maybe), time series data, functional PCA 

-Univariate statistics are most appropriate to use when you have one outcome or measured variable and have planned inferences based on *a priori* hypotheses.  

## Common methods in multivariate analysis

Insert table of commonly used mulitvariate analyses and the type of data needed to conduct said analysis 
Rows: one table, two table, and multi-table (2+) analyses for quantitative, qualitative, and mixed data sets 
Columns: Variable/data, Analysis, Results/output

note we can use this table as a kind of index for people to find the type of analysis they should do based on the type of data they are wanting to analyses
```{r echo=FALSE, results='asis'}
library(knitr)

TableCols <- c("Type of Data", "Data Structure","Analysis", "Results") 
Quant1 <- c("Quantitative","Single Table","PCA","factor scores and column loadings")
Quant2 <- c("Quantitative", "Two Tables", "PLS", "insert")
Quant3 <- c("Quantitative", "Two Tables", "BADA", "insert")
Quant4 <- c("Quantitative", "Multiple (2+) Tables", "MFA", "insert")
Quant5 <- c("Quantitative", "Multiple (2+) TAbles", "Statis", "insert")
Qual1 <- c("Qualitative", "Single Table", "CA", "insert")
Qual2 <- c("Qualitative", "Two or More Tables", "MCA", "insert")
Qual3 <- c("Qualitative", "Two or More Tables", "PLS-CA", "insert")
Qual4 <- c("Mixed", "Two or More Tables", "Mixed PLS", "insert")
tb <- rbind.data.frame(Quant1, Quant2, Quant3, Quant4, Quant5, Qual1, Qual2, Qual3, Qual4) 
colnames(tb) <- TableCols


kable(x = tb, row.names = FALSE,col.names = TableCols ,caption = "Comparison between Multivariate and Univariate Analyses")
```
