# Principal Component Analysis (PCA) {-}

# PCA introduction? {#pca_intro}

## When should you do a PCA?

## How PCA is different from factor analysis and item analysis?

## What does PCA do?

Principal component analysis (PCA) is used to analyze one table of quantitative data. PCA mixes the input variables to give new variables, called principal components (or factors, or latent variables). The first principal component is the best fit of line that maximizes the inertia---variance in 3-D (and beyond) space---of the cloud of data points. Subsequent components are defined as orthogonal to previous components, and maximize the remaining inertia. 

PCA gives one map for the rows (called factor scores), and one map for the columns (called loadings). These 2 maps are related, because they both are described by the same components. However, these 2 maps project different kinds of information onto the components, and so they are *interpreted differently*. Factor scores are the coordinates of the row observations. They are interpreted by the distances between them, and their distance from the origin. Loadings describe the column variables. Loadings are interpreted by the angle between them, and their distance from the origin. 

The distance from the origin is important in both maps, because squared distance from the mean is inertia (variance, information; see sum of squares as in ANOVA/regression). Because of the Pythagorean Theorem, the total information contributed by a data point (its squared distance to the origin) is also equal to the sum of its squared factor scores. 


## What are expected from PCA?

## How do I do PCA?

## Show me the math






